### ISSUE TITLE
UK ERC dataset 관련

### ISSUE THREAD

**Issue by ch-shin** [makinarocks/awesome-industrial-machine-datasets#5]
안녕하세요! 좋은 자료 감사드립니다.

다름이 아니라 리스트에 있는 데이터 중 UK ERC dataset 관련하여, 문의드릴게 있어 이슈 남깁니다.

1. 일반적으로 이 데이터셋은 UK-DALE 데이터셋으로 부르는 걸로 알고 있고, 설명도 UK-DALE로 되어있는것 같은데 UK ERC라고 이름붙이신 이유가 있을까요?
2. 데이터 링크가 'www.doc.ic.ac.uk/ ∼ dk3810/data'로 되어있는데, 띄어쓰기로 인해 하이퍼링크가 제대로 걸려있지 않은 것 같습니다. 그런데 띄어쓰기 없애도 데이터를 받을 수 있는 곳이 제대로 안 뜨는 것 같습니다.
(저는 논문 쓰면서 'https://data.ukedc.rl.ac.uk/browse/edc/efficiency/residential/EnergyConsumption/Domestic/UK-DALE-2017' 에서 데이터를 받았었는데 이게 nature scientific data 논문에 해당하는건지 모르겠네요.)

감사합니다.

**Comment by JeonMinkyu** [comment]
피드백 감사합니다! 
1. 다운로드 받는 링크가 UK ERC로 넘어가고 두개의 키워드로 같은 데이터가 나와서 그렇게 이름을 지었습니다. 그러나 논문상의 표기도 그렇고 실제 데이터셋 이름이 UK-DALE인것 같아 수정하였습니다. 감사합니다
2. 데이터 링크는 README.md 제목에 하이퍼링크로 걸어두었습니다. 거기서 이동되는 페이지에서 다운받아주시면 감사하겠습니다.

**Comment by ch-shin** [comment]
반영 감사합니다!
